on: 
  push:
    branches:
      - main
  
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Install Dependencies
      run: composer install -q --nosi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.justinwebdev.co.nz
        username: justinwe
        password: 69mG28C[Mky@vT
        server-dir: /public_html/dev/